name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.c"
      - "**.py"
      - "**.cpp"
      - "**.pyx"
      - "**.build"

permissions:
  contents: read

jobs:
  meson_versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meson_version: ["1.0.0", "1.1.0", "1.2.0", "1.3.0", "latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build System
      run: |
        if [[ "${{ matrix.meson_version }}" == "latest" ]]; then
          pip install meson ninja cython
        else
          pip install "meson==${{ matrix.meson_version }}" "ninja==1.11.1" "cython==3.0.8"
        fi
        sudo apt-get install -y gcc
    - name: Generate Build Files
      run: |
        python meson-generator.py
    - name: Setup Build Directory
      run: |
        meson setup builddir
    - name: Compile Source Code
      run: |
        meson compile -C builddir
